export const menus = [
  {
    restaurant_id: "312393",
    items: [
      {
        item_id: "R01I01",
        name: "Rava Dosa",
        price: 34790,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R01I02",
        name: "Margherita Pizza",
        price: 29195,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R01I03",
        name: "Ice Cream",
        price: 10741,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R01I04",
        name: "Masala Dosa",
        price: 17632,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R01I05",
        name: "Paneer Butter Masala",
        price: 16020,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R01I06",
        name: "Veg Biryani",
        price: 21489,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R01I07",
        name: "Veggie Pizza",
        price: 21260,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R01I08",
        name: "Gulab Jamun",
        price: 14573,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R01I09",
        name: "Naan",
        price: 26259,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R01I10",
        name: "Arrabiata Pasta",
        price: 29281,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R01I11",
        name: "Chicken Biryani",
        price: 14081,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R01I12",
        name: "Brownie",
        price: 34622,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R01I13",
        name: "Veg Salad",
        price: 17200,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R01I14",
        name: "Tandoori Chicken",
        price: 25762,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R01I15",
        name: "Dal Fry",
        price: 12894,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R01I16",
        name: "Pepperoni Pizza",
        price: 28384,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R01I17",
        name: "Alfredo Pasta",
        price: 13783,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R01I18",
        name: "French Fries",
        price: 18970,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R01I19",
        name: "Idli Sambar",
        price: 28876,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R01I20",
        name: "Chicken Pasta",
        price: 10971,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
    ],
  },
  {
    restaurant_id: "824424",
    items: [
      {
        item_id: "R02I01",
        name: "Paneer Butter Masala",
        price: 17913,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R02I02",
        name: "Veg Biryani",
        price: 27272,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R02I03",
        name: "Veggie Pizza",
        price: 19572,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R02I04",
        name: "Rava Dosa",
        price: 27124,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R02I05",
        name: "Masala Dosa",
        price: 28014,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R02I06",
        name: "Cheese Balls",
        price: 18761,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R02I07",
        name: "Naan",
        price: 32917,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R02I08",
        name: "Chicken Pasta",
        price: 30079,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R02I09",
        name: "Margherita Pizza",
        price: 31274,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R02I10",
        name: "Dal Fry",
        price: 20984,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R02I11",
        name: "Idli Sambar",
        price: 13629,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R02I12",
        name: "Ice Cream",
        price: 21294,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R02I13",
        name: "Alfredo Pasta",
        price: 17924,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R02I14",
        name: "Brownie",
        price: 13460,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R02I15",
        name: "Gulab Jamun",
        price: 33571,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R02I16",
        name: "Pepperoni Pizza",
        price: 32415,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R02I17",
        name: "Arrabiata Pasta",
        price: 24180,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R02I18",
        name: "French Fries",
        price: 28405,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R02I19",
        name: "Veg Salad",
        price: 20282,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R02I20",
        name: "Chicken Biryani",
        price: 18818,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
    ],
  },
  {
    restaurant_id: "934128",
    items: [
      {
        item_id: "R03I01",
        name: "Arrabiata Pasta",
        price: 19351,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R03I02",
        name: "Brownie",
        price: 18182,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R03I03",
        name: "Chicken Biryani",
        price: 10328,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R03I04",
        name: "Veg Salad",
        price: 31501,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R03I05",
        name: "Naan",
        price: 28625,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R03I06",
        name: "Ice Cream",
        price: 31987,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R03I07",
        name: "French Fries",
        price: 26288,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R03I08",
        name: "Gulab Jamun",
        price: 33902,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R03I09",
        name: "Dal Fry",
        price: 28749,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R03I10",
        name: "Cheese Balls",
        price: 22235,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R03I11",
        name: "Tandoori Chicken",
        price: 21944,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R03I12",
        name: "Paneer Butter Masala",
        price: 19074,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R03I13",
        name: "Margherita Pizza",
        price: 32545,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R03I14",
        name: "Masala Dosa",
        price: 17316,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R03I15",
        name: "Chicken Pasta",
        price: 29056,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R03I16",
        name: "Veg Biryani",
        price: 25604,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R03I17",
        name: "Pepperoni Pizza",
        price: 20401,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R03I18",
        name: "Idli Sambar",
        price: 32854,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R03I19",
        name: "Rava Dosa",
        price: 14478,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R03I20",
        name: "Alfredo Pasta",
        price: 20471,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
    ],
  },
  {
    restaurant_id: "1106214",
    items: [
      {
        item_id: "R04I01",
        name: "Veg Salad",
        price: 11805,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R04I02",
        name: "Veg Biryani",
        price: 14296,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R04I03",
        name: "Gulab Jamun",
        price: 15530,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R04I04",
        name: "Paneer Butter Masala",
        price: 19192,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R04I05",
        name: "French Fries",
        price: 26519,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R04I06",
        name: "Arrabiata Pasta",
        price: 19767,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R04I07",
        name: "Dal Fry",
        price: 19693,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R04I08",
        name: "Cheese Balls",
        price: 21753,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R04I09",
        name: "Pepperoni Pizza",
        price: 28164,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R04I10",
        name: "Veggie Pizza",
        price: 33118,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R04I11",
        name: "Brownie",
        price: 23234,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R04I12",
        name: "Chicken Biryani",
        price: 21296,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R04I13",
        name: "Chicken Pasta",
        price: 16147,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R04I14",
        name: "Naan",
        price: 32111,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R04I15",
        name: "Tandoori Chicken",
        price: 30903,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R04I16",
        name: "Masala Dosa",
        price: 25490,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R04I17",
        name: "Idli Sambar",
        price: 10557,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R04I18",
        name: "Ice Cream",
        price: 30593,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R04I19",
        name: "Alfredo Pasta",
        price: 21858,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R04I20",
        name: "Rava Dosa",
        price: 19810,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
    ],
  },
  {
    restaurant_id: "1099083",
    items: [
      {
        item_id: "R05I01",
        name: "Alfredo Pasta",
        price: 18402,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R05I02",
        name: "Veg Biryani",
        price: 15681,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R05I03",
        name: "French Fries",
        price: 23551,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R05I04",
        name: "Margherita Pizza",
        price: 19113,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R05I05",
        name: "Paneer Butter Masala",
        price: 32536,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R05I06",
        name: "Ice Cream",
        price: 29232,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R05I07",
        name: "Chicken Pasta",
        price: 34316,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R05I08",
        name: "Dal Fry",
        price: 22401,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R05I09",
        name: "Masala Dosa",
        price: 11533,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R05I10",
        name: "Gulab Jamun",
        price: 21841,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R05I11",
        name: "Rava Dosa",
        price: 30941,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R05I12",
        name: "Veg Salad",
        price: 11419,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R05I13",
        name: "Tandoori Chicken",
        price: 29153,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R05I14",
        name: "Naan",
        price: 23598,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R05I15",
        name: "Idli Sambar",
        price: 24351,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R05I16",
        name: "Veggie Pizza",
        price: 14045,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R05I17",
        name: "Arrabiata Pasta",
        price: 21235,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R05I18",
        name: "Pepperoni Pizza",
        price: 14949,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R05I19",
        name: "Chicken Biryani",
        price: 10964,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R05I20",
        name: "Brownie",
        price: 29192,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
    ],
  },
  {
    restaurant_id: "813673",
    items: [
      {
        item_id: "R06I01",
        name: "Chicken Pasta",
        price: 11464,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R06I02",
        name: "Alfredo Pasta",
        price: 13122,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R06I03",
        name: "Cheese Balls",
        price: 16686,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R06I04",
        name: "Margherita Pizza",
        price: 27591,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R06I05",
        name: "Masala Dosa",
        price: 13387,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R06I06",
        name: "French Fries",
        price: 34045,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R06I07",
        name: "Naan",
        price: 27264,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R06I08",
        name: "Brownie",
        price: 33378,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R06I09",
        name: "Rava Dosa",
        price: 12776,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R06I10",
        name: "Gulab Jamun",
        price: 23196,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R06I11",
        name: "Arrabiata Pasta",
        price: 32148,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R06I12",
        name: "Ice Cream",
        price: 27181,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R06I13",
        name: "Idli Sambar",
        price: 14354,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R06I14",
        name: "Chicken Biryani",
        price: 23139,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R06I15",
        name: "Pepperoni Pizza",
        price: 32608,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R06I16",
        name: "Veggie Pizza",
        price: 26249,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R06I17",
        name: "Veg Biryani",
        price: 11995,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R06I18",
        name: "Paneer Butter Masala",
        price: 13841,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R06I19",
        name: "Dal Fry",
        price: 14680,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R06I20",
        name: "Tandoori Chicken",
        price: 24466,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
    ],
  },
  {
    restaurant_id: "813682",
    items: [
      {
        item_id: "R07I01",
        name: "Gulab Jamun",
        price: 9996,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R07I02",
        name: "Veg Biryani",
        price: 24399,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R07I03",
        name: "Margherita Pizza",
        price: 20828,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R07I04",
        name: "Idli Sambar",
        price: 19171,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R07I05",
        name: "Rava Dosa",
        price: 33219,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R07I06",
        name: "Tandoori Chicken",
        price: 12004,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R07I07",
        name: "Veggie Pizza",
        price: 15592,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R07I08",
        name: "French Fries",
        price: 29363,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R07I09",
        name: "Chicken Biryani",
        price: 27043,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R07I10",
        name: "Naan",
        price: 20830,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R07I11",
        name: "Alfredo Pasta",
        price: 23540,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R07I12",
        name: "Cheese Balls",
        price: 25583,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R07I13",
        name: "Ice Cream",
        price: 16851,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R07I14",
        name: "Veg Salad",
        price: 15226,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R07I15",
        name: "Chicken Pasta",
        price: 25254,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R07I16",
        name: "Paneer Butter Masala",
        price: 22161,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R07I17",
        name: "Brownie",
        price: 14641,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R07I18",
        name: "Pepperoni Pizza",
        price: 30796,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R07I19",
        name: "Masala Dosa",
        price: 20181,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R07I20",
        name: "Dal Fry",
        price: 20403,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
    ],
  },
  {
    restaurant_id: "813676",
    items: [
      {
        item_id: "R08I01",
        name: "Dal Fry",
        price: 31838,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R08I02",
        name: "Margherita Pizza",
        price: 24708,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R08I03",
        name: "Chicken Biryani",
        price: 30620,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R08I04",
        name: "Paneer Butter Masala",
        price: 13932,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R08I05",
        name: "Veggie Pizza",
        price: 21847,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R08I06",
        name: "Alfredo Pasta",
        price: 11030,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R08I07",
        name: "Naan",
        price: 24195,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R08I08",
        name: "Arrabiata Pasta",
        price: 23353,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R08I09",
        name: "Pepperoni Pizza",
        price: 14498,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R08I10",
        name: "Masala Dosa",
        price: 29257,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R08I11",
        name: "Gulab Jamun",
        price: 21559,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R08I12",
        name: "French Fries",
        price: 15183,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R08I13",
        name: "Ice Cream",
        price: 30421,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R08I14",
        name: "Veg Salad",
        price: 34666,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R08I15",
        name: "Cheese Balls",
        price: 24525,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R08I16",
        name: "Veg Biryani",
        price: 33377,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R08I17",
        name: "Idli Sambar",
        price: 30417,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R08I18",
        name: "Chicken Pasta",
        price: 10197,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R08I19",
        name: "Rava Dosa",
        price: 31872,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R08I20",
        name: "Tandoori Chicken",
        price: 18284,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
    ],
  },
  {
    restaurant_id: "REST009",
    items: [
      {
        item_id: "R09I01",
        name: "French Fries",
        price: 14841,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R09I02",
        name: "Margherita Pizza",
        price: 20067,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R09I03",
        name: "Masala Dosa",
        price: 10050,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R09I04",
        name: "Alfredo Pasta",
        price: 14159,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R09I05",
        name: "Paneer Butter Masala",
        price: 26636,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R09I06",
        name: "Rava Dosa",
        price: 17885,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R09I07",
        name: "Brownie",
        price: 11389,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R09I08",
        name: "Dal Fry",
        price: 17856,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R09I09",
        name: "Arrabiata Pasta",
        price: 11049,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R09I10",
        name: "Veggie Pizza",
        price: 30223,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R09I11",
        name: "Idli Sambar",
        price: 23541,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R09I12",
        name: "Tandoori Chicken",
        price: 20515,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R09I13",
        name: "Ice Cream",
        price: 19547,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R09I14",
        name: "Naan",
        price: 14813,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R09I15",
        name: "Pepperoni Pizza",
        price: 20980,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R09I16",
        name: "Chicken Biryani",
        price: 20461,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R09I17",
        name: "Gulab Jamun",
        price: 11273,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R09I18",
        name: "Chicken Pasta",
        price: 26192,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R09I19",
        name: "Veg Salad",
        price: 24101,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R09I20",
        name: "Veg Biryani",
        price: 28600,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
    ],
  },
  {
    restaurant_id: "REST010",
    items: [
      {
        item_id: "R10I01",
        name: "Chicken Biryani",
        price: 31941,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R10I02",
        name: "Veg Salad",
        price: 26670,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R10I03",
        name: "Chicken Pasta",
        price: 22804,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R10I04",
        name: "Veg Biryani",
        price: 29662,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R10I05",
        name: "Tandoori Chicken",
        price: 18611,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R10I06",
        name: "Brownie",
        price: 31551,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R10I07",
        name: "Cheese Balls",
        price: 24690,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R10I08",
        name: "Paneer Butter Masala",
        price: 24358,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R10I09",
        name: "Alfredo Pasta",
        price: 33882,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R10I10",
        name: "Margherita Pizza",
        price: 26967,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R10I11",
        name: "Masala Dosa",
        price: 30308,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R10I12",
        name: "Arrabiata Pasta",
        price: 25174,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R10I13",
        name: "Gulab Jamun",
        price: 18475,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R10I14",
        name: "Ice Cream",
        price: 15470,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R10I15",
        name: "Veggie Pizza",
        price: 31801,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R10I16",
        name: "Dal Fry",
        price: 22772,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R10I17",
        name: "Idli Sambar",
        price: 31835,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R10I18",
        name: "Rava Dosa",
        price: 30646,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R10I19",
        name: "French Fries",
        price: 17487,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R10I20",
        name: "Naan",
        price: 28809,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
    ],
  },
  {
    restaurant_id: "REST011",
    items: [
      {
        item_id: "R11I01",
        name: "Ice Cream",
        price: 18970,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R11I02",
        name: "Paneer Butter Masala",
        price: 34352,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R11I03",
        name: "Tandoori Chicken",
        price: 24115,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R11I04",
        name: "Margherita Pizza",
        price: 17750,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R11I05",
        name: "Dal Fry",
        price: 19472,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R11I06",
        name: "Gulab Jamun",
        price: 13895,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R11I07",
        name: "Pepperoni Pizza",
        price: 14555,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R11I08",
        name: "Veggie Pizza",
        price: 23420,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R11I09",
        name: "Naan",
        price: 29761,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R11I10",
        name: "Rava Dosa",
        price: 21154,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R11I11",
        name: "Chicken Pasta",
        price: 19184,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R11I12",
        name: "Arrabiata Pasta",
        price: 24792,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R11I13",
        name: "Cheese Balls",
        price: 25587,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R11I14",
        name: "Brownie",
        price: 14134,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R11I15",
        name: "Veg Biryani",
        price: 32734,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R11I16",
        name: "Veg Salad",
        price: 10374,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R11I17",
        name: "Chicken Biryani",
        price: 31075,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R11I18",
        name: "Masala Dosa",
        price: 27372,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R11I19",
        name: "Idli Sambar",
        price: 33949,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R11I20",
        name: "Alfredo Pasta",
        price: 25352,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
    ],
  },
  {
    restaurant_id: "REST012",
    items: [
      {
        item_id: "R12I01",
        name: "Veggie Pizza",
        price: 12270,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R12I02",
        name: "Dal Fry",
        price: 23378,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R12I03",
        name: "Margherita Pizza",
        price: 31386,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R12I04",
        name: "French Fries",
        price: 30261,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R12I05",
        name: "Pepperoni Pizza",
        price: 12961,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R12I06",
        name: "Gulab Jamun",
        price: 19524,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R12I07",
        name: "Chicken Biryani",
        price: 12936,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R12I08",
        name: "Tandoori Chicken",
        price: 22869,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R12I09",
        name: "Veg Biryani",
        price: 32148,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R12I10",
        name: "Paneer Butter Masala",
        price: 11126,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R12I11",
        name: "Naan",
        price: 19477,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R12I12",
        name: "Arrabiata Pasta",
        price: 11416,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R12I13",
        name: "Ice Cream",
        price: 31393,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R12I14",
        name: "Rava Dosa",
        price: 21565,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R12I15",
        name: "Idli Sambar",
        price: 13331,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R12I16",
        name: "Masala Dosa",
        price: 24022,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R12I17",
        name: "Veg Salad",
        price: 32338,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R12I18",
        name: "Cheese Balls",
        price: 28455,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R12I19",
        name: "Chicken Pasta",
        price: 31657,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R12I20",
        name: "Brownie",
        price: 17789,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
    ],
  },
  {
    restaurant_id: "REST013",
    items: [
      {
        item_id: "R13I01",
        name: "Margherita Pizza",
        price: 32036,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R13I02",
        name: "Dal Fry",
        price: 21658,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R13I03",
        name: "Idli Sambar",
        price: 31939,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R13I04",
        name: "Veg Salad",
        price: 22028,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R13I05",
        name: "French Fries",
        price: 24155,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R13I06",
        name: "Brownie",
        price: 20022,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R13I07",
        name: "Chicken Biryani",
        price: 30837,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R13I08",
        name: "Masala Dosa",
        price: 31668,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R13I09",
        name: "Veggie Pizza",
        price: 24182,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R13I10",
        name: "Ice Cream",
        price: 11583,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R13I11",
        name: "Cheese Balls",
        price: 29047,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R13I12",
        name: "Veg Biryani",
        price: 19767,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R13I13",
        name: "Naan",
        price: 10953,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R13I14",
        name: "Rava Dosa",
        price: 24536,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R13I15",
        name: "Chicken Pasta",
        price: 33592,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R13I16",
        name: "Alfredo Pasta",
        price: 21989,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R13I17",
        name: "Gulab Jamun",
        price: 29704,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R13I18",
        name: "Tandoori Chicken",
        price: 28421,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R13I19",
        name: "Pepperoni Pizza",
        price: 31704,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R13I20",
        name: "Arrabiata Pasta",
        price: 25103,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
    ],
  },
  {
    restaurant_id: "REST014",
    items: [
      {
        item_id: "R14I01",
        name: "Gulab Jamun",
        price: 29988,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R14I02",
        name: "Alfredo Pasta",
        price: 29365,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?alfredo,food",
      },
      {
        item_id: "R14I03",
        name: "Ice Cream",
        price: 33607,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R14I04",
        name: "Rava Dosa",
        price: 31432,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R14I05",
        name: "Margherita Pizza",
        price: 26316,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
      {
        item_id: "R14I06",
        name: "Masala Dosa",
        price: 18489,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R14I07",
        name: "Cheese Balls",
        price: 29320,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R14I08",
        name: "Paneer Butter Masala",
        price: 26908,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R14I09",
        name: "Veg Salad",
        price: 28825,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R14I10",
        name: "Idli Sambar",
        price: 16975,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R14I11",
        name: "Dal Fry",
        price: 15778,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R14I12",
        name: "Chicken Pasta",
        price: 32559,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R14I13",
        name: "Pepperoni Pizza",
        price: 22699,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R14I14",
        name: "Chicken Biryani",
        price: 27270,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R14I15",
        name: "Veggie Pizza",
        price: 14236,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R14I16",
        name: "French Fries",
        price: 26013,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R14I17",
        name: "Veg Biryani",
        price: 33871,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R14I18",
        name: "Brownie",
        price: 9589,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R14I19",
        name: "Tandoori Chicken",
        price: 24758,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R14I20",
        name: "Arrabiata Pasta",
        price: 16878,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
    ],
  },
  {
    restaurant_id: "REST015",
    items: [
      {
        item_id: "R15I01",
        name: "Paneer Butter Masala",
        price: 12407,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?paneer,food",
      },
      {
        item_id: "R15I02",
        name: "Naan",
        price: 17014,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?naan,food",
      },
      {
        item_id: "R15I03",
        name: "Brownie",
        price: 30724,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?brownie,food",
      },
      {
        item_id: "R15I04",
        name: "Chicken Pasta",
        price: 12715,
        is_veg: false,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R15I05",
        name: "Pepperoni Pizza",
        price: 20052,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?pepperoni,food",
      },
      {
        item_id: "R15I06",
        name: "Ice Cream",
        price: 23405,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?ice,food",
      },
      {
        item_id: "R15I07",
        name: "Dal Fry",
        price: 23006,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?dal,food",
      },
      {
        item_id: "R15I08",
        name: "French Fries",
        price: 22523,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?french,food",
      },
      {
        item_id: "R15I09",
        name: "Gulab Jamun",
        price: 33937,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?gulab,food",
      },
      {
        item_id: "R15I10",
        name: "Arrabiata Pasta",
        price: 32914,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?arrabiata,food",
      },
      {
        item_id: "R15I11",
        name: "Veg Biryani",
        price: 9516,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R15I12",
        name: "Veg Salad",
        price: 14474,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veg,food",
      },
      {
        item_id: "R15I13",
        name: "Cheese Balls",
        price: 24427,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?cheese,food",
      },
      {
        item_id: "R15I14",
        name: "Tandoori Chicken",
        price: 13924,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?tandoori,food",
      },
      {
        item_id: "R15I15",
        name: "Veggie Pizza",
        price: 22681,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?veggie,food",
      },
      {
        item_id: "R15I16",
        name: "Masala Dosa",
        price: 19109,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?masala,food",
      },
      {
        item_id: "R15I17",
        name: "Idli Sambar",
        price: 20388,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?idli,food",
      },
      {
        item_id: "R15I18",
        name: "Chicken Biryani",
        price: 16388,
        is_veg: false,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?chicken,food",
      },
      {
        item_id: "R15I19",
        name: "Rava Dosa",
        price: 21366,
        is_veg: true,
        in_stock: false,
        image_url: "https://source.unsplash.com/featured/?rava,food",
      },
      {
        item_id: "R15I20",
        name: "Margherita Pizza",
        price: 29433,
        is_veg: true,
        in_stock: true,
        image_url: "https://source.unsplash.com/featured/?margherita,food",
      },
    ],
  },
];
